# define the two containers
services:
  psql-db:
    # pull the postgres image from DockerHub
    image: postgres:latest
    container_name: psql-db
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /barbershop/secrets/postgres_password
      POSTGRES_DB: db
      DATABASE_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      # used in flask container depends_on condition to wait for the DB to be ready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 5

  flask-backend:
    build: ./barbershop
    container_name: flask-backend
    ports:
      - "5000:5000"
    depends_on:
      psql-db:
        # waiting for the database to be ready
        condition: service_healthy
    environment:
      RDS_USERNAME: ${POSTGRES_USER}
      RDS_PASSWORD: ${POSTGRES_PASSWORD}
      RDS_HOSTNAME: psql-db
      RDS_PORT: 5432
      RDS_DB_NAME: ${POSTGRES_DB}
    volumes:
      - ./flask/app:/app/app

secrets:
  postgres_user:
    file: .barbershop/secrets/postgres_user.txt
  postgres_password:
    file: .barbershop/secrets/postgres_password.txt

volumes:
  # to persist the database tables
  db-volume: