FROM python:3.11.8

RUN apt-get update && \
    apt-get install -y postgresql-client-13

WORKDIR /barbershop

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app app
COPY app.py .

EXPOSE 5000

CMD [ "python", "app.py"]