services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - ./barbershopdb.sql:/docker-entrypoint-initdb.d/barbershopdb.sql
  
  flask-backend:
    build: ./barbershop
    container_name: flask-backend
    ports:
      - "5000:5000"
    depends_on:
      psql-db:
        # waiting for the database to be ready
        condition: service_healthy
    environment:
      RDS_USERNAME: ${POSTGRES_USER}
      RDS_PASSWORD: ${POSTGRES_PASSWORD}
      RDS_HOSTNAME: postgres-db
      RDS_PORT: 5432
      RDS_DB_NAME: ${POSTGRES_DB}
    volumes:
      - ./barbershop:/app/app